version: 1.0.{build}
image: Previous Visual Studio 2017
clone_folder: C:\app\
build:
  verbosity: minimal
before_deploy:
- sh: >-
    docker build -t netcore2-project-heroku-skell-app .
    docker run -p 5000:80 netcore2-project-heroku-skell-app